[source]
username = "source_username"
password = "source_password"
host = "source_host"
port = "source_port"
service_name = "source_service_name"

[destination]
username = "dest_username"
password = "dest_password"
host = "dest_host"
port = "dest_port"
service_name = "dest_service_name"